  #datasource:
  #  url: jdbc:h2:mem:ear
  #  driver-class-name: org.h2.Driver
  #  username: e
  #  password: 69
  #h2:
  #  console:
  #    enabled: true
  #    path: /h2
  #jpa:
  #  hibernate:
  #    ddl-auto: update
  #  show-sql: true
  #  properties:
  #    hibernate:
  #      dialect: org.hibernate.dialect.H2Dialect
  #  defer-datasource-initialization: true
  server:
    servlet:
      context-path: /club-evidence

  spring:
    datasource:
      url: jdbc:postgresql://kbss.felk.cvut.cz:5433/ear2023zs_13
      username: ear2023zs_13
      password: ear2023zs_13pass
      driver-class-name: org.postgresql.Driver
    jpa:
      database-platform: org.hibernate.dialect.PostgreSQLDialect
      properties:
        hibernate:
          hbm2ddl:
            auto: create
  logging:
    level:
      org.springframework.security.web: DEBUG

